"""init

Revision ID: 20db75ebafda
Revises: 30d5e67f637a
Create Date: 2024-07-11 16:53:28.412020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20db75ebafda'
down_revision = '30d5e67f637a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
